### ISSUE TITLE
add a / endpoint

### ISSUE THREAD

**Issue by willkg** [mozilla/antenna#102]
It's irritating to have `/` kick up an HTTP 500. We should add an endpoint that returns a page that says, "Hi. My name is Antenna."

**Comment by willkg** [comment]
@milescrabill Any thoughts here? Should we return an HTTP 200 page? Is it better to return an HTTP 404 for some ops-y reason?

**Comment by milescrabill** [comment]
200 is A-OK!

**Comment by willkg** [comment]
Fixed in PR #108.
