### ISSUE TITLE
Document how to do local Firefox end-to-end testing

### ISSUE THREAD

**Issue by peterbe** [mozilla/antenna#27]
There's an `about:config` to override the URL to where Breakpad should send to. There's also an add-on (that's probably out of date and not signed) called crashmenow. 

We should document, in the readme or something, how to use these tools to fully test antenna with a local firefox and a local antenna server.

**Comment by willkg** [comment]
We have documentation on how to send crashes to Antenna via a variety of ways here:

http://antenna.readthedocs.io/en/latest/breakpad_reporting.html#testing-breakpad-crash-reporting

Pretty sure that covers this.
