### ISSUE TITLE
Respect 'Throttleable'

### ISSUE THREAD

**Issue by peterbe** [mozilla/antenna#31]
When you submit crashes from `about:crashes` it sets `Throttleable=0` in the form data. Our new throttler needs to respect this. 
See https://dxr.mozilla.org/mozilla-central/source/toolkit/crashreporter/CrashSubmit.jsm#282

**Comment by willkg** [comment]
Is this something the current collector does? Doesn't seem like it does.

Given that, should we fix the current collector? Figure we won't be deploying antenna until like July or August.

**Comment by peterbe** [comment]
> Is this something the current collector does? Doesn't seem like it does.

Shame if it didn't. But likely to be the case.

> Given that, should we fix the current collector?

No. I don't think so. 

But it would be nice if the new one supports this.

**Comment by willkg** [comment]
Closing this out as it'll get covered in #8.
