### ISSUE TITLE
implement ops Dockerflow status endpoints

### ISSUE THREAD

**Issue by willkg** [mozilla/antenna#41]
Antenna is going to be run by a different ops group than we were originally envisioning when I started it months ago.

They have a standard for status endpoints which is mentioned here:

https://github.com/mozilla-services/Dockerflow/#containerized-app-requirements

This issue covers implementing that.

One thing to note is that any basic auth stuff will be handled in nginx configuration--we don't have to worry about that in Python land.

* [x] Respond to `/__version__` with the contents of `/app/version.json`.
* [ ] Respond to `/__heartbeat__` with a HTTP 200 or 5xx on error. This should check backing services like a database for connectivity.
* [ ] Respond to `/__lbheartbeat__` with an HTTP 200. This is for load balancer checks and should not check backing services.

**Comment by jdotpz** [comment]
This is awesome, thanks for migrating to the new setup!

**Comment by willkg** [comment]
I nixed the old health check code that I thought was broken and didn't work, but it turns out we were using it for -dev. Oops. Sorry about that.

I implemented the `/__version__` endpoint so that I can verify what's been deployed.

There are a few more endpoints to implement, so I'm going to leave this open.

**Comment by willkg** [comment]
Implemented the last two endpoints in PR #96.
