### ISSUE TITLE
ditch settings* files and go with environment and env files

### ISSUE THREAD

**Issue by willkg** [mozilla/antenna#42]
This issue covers ditching the settings* files and instead going with environment and an env file specified by ANTENNA_ENV and defaulting to whatever makes sense. Then we need to update docker container, circle setup and any documentation that talks about INI files.

Down with INI! Up with people!

**Comment by milescrabill** [comment]
It's easy for me to just set env variables in the container, you don't necessarily need an env file :)

Up with people!

**Comment by willkg** [comment]
This is less of a "make @milescrabill job easier" and more of a "reduce the complexity of the app and docs" kind of thing.

INI files have a different syntax than environment things, so keeping everything "environment-like" makes life easier.

**Comment by willkg** [comment]
Nixed the INI file stuff in PR #65. I didn't add support for env files--I figure I'll push that off until later if there's a need.

Closing this out.

**Comment by milescrabill** [comment]
No need for env files on my end :)
