### ISSUE TITLE
circle ci deploy failures

### ISSUE THREAD

**Issue by willkg** [mozilla/antenna#66]
I keep getting these emails from Circle after I merge a PR:

```
It looks like we couldn't infer test settings for your project. Refer to our "Setting your build up manually" document to get started. It should only take a few minutes.
Failing command: Checkout using deploy key: d6:32:06:c5:1f:65:a6:a7:ae:18:f2:d4:69:9c:c2:a4
Exit code: 128
Output:

Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

git command i returned 128: 

The rest of your commands (they all ran successfully):

    Starting the build
    Start container
    Enable SSH
    Restore source cache
    Disable SSH
```

That may have started happening after I moved the tests to a different directory, but I'm not sure why that would cause a problem with reading from the remote repository.

This issue covers fixing whatever is causing this.

**Comment by willkg** [comment]
It's happened for every PR merge over the last couple of days, so I don't think this is an ephemeral problem.

@milescrabill Any ideas?

**Comment by milescrabill** [comment]
Is this fixed?

**Comment by willkg** [comment]
(Between the last two comments, we chatted on IRC and then @milescrabill fixed a bunch of things.)

I merged something earlier and just verified that it got deployed ok. We're all set. Thank you!
